# Generated by Django 4.2.1 on 2023-11-07 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_candidate_votes_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_hash', models.CharField(default='', max_length=64)),
                ('hash', models.CharField(default='', max_length=64)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('nonce', models.IntegerField(default=0)),
            ],
        ),
    ]
