# Generated by Django 4.2.1 on 2023-11-07 08:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_block'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.AddField(
            model_name='vote',
            name='hash',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='vote',
            name='nonce',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vote',
            name='previous_hash',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='vote',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
