# Generated by Django 4.2.1 on 2023-11-07 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_block_blockchain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Block',
        ),
        migrations.DeleteModel(
            name='Blockchain',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='hash',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='nonce',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='previous_hash',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='timestamp',
        ),
    ]
